// Generated by gulp icon - do not modify manually

import * as React from 'react';

const iconList = [
  'back',
  'circle',
  'clock',
  'close',
  'favorite',
  'heart',
  'heart-on',
  'more',
  'play',
  'setting',
  'share',
  'wechat',
];

export interface IconProps {
  color?: string;
  className?: string;
  height?: string | number;
  kind?: string | any;
  onClick?: () => void;
  preview?: boolean;
  size?: string | number;
  style?: any;
  width?: string | number;
  wrapperStyle?: any;
}
export default class Icon extends React.Component<IconProps, {}> {
  static defaultProps = {
    className: '',
    color: 'currentColor',
    size: '100%',
  };

  render() {
    const { kind, preview } = this.props;
    return preview ? this.renderPreview() : this.renderIcon(kind);
  }

  renderPreview() {
    return <div>{iconList.map(kind => this.renderPreviewKind(kind))}</div>;
  }

  renderIcon(kind: string) {
    const { wrapperStyle } = this.props;
    if (wrapperStyle) {
      return <div style={wrapperStyle}>{this.getIcon(kind)}</div>;
    }
    return this.getIcon(kind);
  }

  renderPreviewKind(kind: string) {
    return (
      <div key={kind}>
        <h3>&lt;Icon kind="{kind}" /&gt;</h3>
        {this.renderIcon(kind)}
      </div>
    );
  }

  getIcon(kind: string) {
    const { color, height, onClick, size, style, width, className } = this.props;

    switch (kind) {
      case 'back':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 580.06 1024"
          >
            <title>back</title>
            <path d="M506.61 1024L0 512 506.61 0 580 71.85 144.57 512l435.49 440.15z" />
          </svg>
        );
      case 'circle':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 1024 1024"
          >
            <title>circle</title>
            <path d="M678.57,27.72a514.31,514.31,0,0,0-341.49,2.94L678.57,370.87Z" fill="#f1765a" />
            <path
              d="M30.08,685.3,372.5,344.18H28.15A514.29,514.29,0,0,0,30.08,685.3Z"
              fill="#f1dd5a"
            />
            <path
              d="M48.4,294.43H531.11L287.6,51.67A514.1,514.1,0,0,0,48.4,294.43Z"
              fill="#f1b35a"
            />
            <path d="M970.67,284.22A514.16,514.16,0,0,0,728.5,47.89V529.06Z" fill="#6c5af1" />
            <path
              d="M295.77,976.23V491.09L51,735A514.07,514.07,0,0,0,295.77,976.23Z"
              fill="#baf259"
            />
            <path
              d="M992,333.56,651.78,675.8H997.23A514.31,514.31,0,0,0,992,333.56Z"
              fill="#5a9ef1"
            />
            <path
              d="M690.06,992.18,345.7,649.11V996.38a514.28,514.28,0,0,0,344.36-4.2Z"
              fill="#5ef15a"
            />
            <path
              d="M977.47,725.55H493.16L739.29,970.91A514.12,514.12,0,0,0,977.47,725.55Z"
              fill="#5ae5f1"
            />
          </svg>
        );
      case 'clock':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 1024 1024"
          >
            <title>clock</title>
            <path d="M512 115.79C730.81 116.91 907.28 295.2 906.16 514S726.75 909.28 507.94 908.16C289.92 907.05 113.77 730 113.78 512c.82-219.26 179-396.48 398.22-396.17M512 0C229.23 0 0 229.23 0 512s229.23 512 512 512 512-229.23 512-512S794.77 0 512 0zm156.62 646.88H479A57.38 57.38 0 0 1 422.1 589V318.84a56.89 56.89 0 1 1 113.77 0v212.27h132.75a57.89 57.89 0 0 1 0 115.77z" />
          </svg>
        );
      case 'close':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 955.73 955.73"
          >
            <title>close</title>
            <path d="M955.73 73.52L883.73 0 477.87 405.18 72 0 0 73.52 405 478 0 882.24l72 73.49 405.87-405.12 405.86 405.12 72-73.49L550.71 478z" />
          </svg>
        );
      case 'favorite':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 899.01 1024"
          >
            <title>favorite</title>
            <polygon
              points="874.69 245.36 449.63 490.96 449.14 490.96 24.32 245.36 449.38 0 874.69 245.36"
              fill="#5a9ef1"
            />
            <polygon
              points="899.01 287.43 899.01 778.39 473.7 1024 473.7 533.03 899.01 287.43"
              fill="#f1765a"
            />
            <polygon
              points="425.06 533.03 425.06 1024 0 778.39 0 287.43 425.06 533.03"
              fill="#f1dd5a"
            />
          </svg>
        );
      case 'heart':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 955.76 853.03"
          >
            <title>heart</title>
            <path d="M681.21 66.47c116.73 1.31 210.39 96.84 209.38 213.58a216.08 216.08 0 0 1-68.7 158.19 65.44 65.44 0 0 0-6.57 7.05L521.4 745.1a338.12 338.12 0 0 1-43.52 39.9 339 339 0 0 1-43.54-39.86L140.49 445.25a66.33 66.33 0 0 0-6.62-7.1 216.09 216.09 0 0 1-68.7-158.1c-1-116.74 92.65-212.27 209.38-213.58a208.24 208.24 0 0 1 155.1 70.06 64.31 64.31 0 0 0 90.77 5.7 65.12 65.12 0 0 0 5.69-5.7 208.24 208.24 0 0 1 155.1-70.06m0-66.47a271.56 271.56 0 0 0-203.33 91.85A271.63 271.63 0 0 0 274.55 0C121.42 1.55-1.48 126.91 0 280.05a281.83 281.83 0 0 0 90.07 207.39h-.46L388.28 792.1c29.87 30.46 59.72 60.9 89.6 60.9s59.73-30.47 89.6-60.93l298.67-304.63h-.45a281.89 281.89 0 0 0 90-207.39C957.23 126.92 834.34 1.56 681.21 0z" />
          </svg>
        );
      case 'heart-on':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 955.76 853.03"
          >
            <title>heart-on</title>
            <path d="M681.21 0a271.59 271.59 0 0 0-203.33 91.85A271.55 271.55 0 0 0 274.53 0C121.41 1.57-1.47 126.92 0 280.05a281.93 281.93 0 0 0 90.06 207.39h-.45L388.28 792.1c29.87 30.46 59.72 60.9 89.6 60.9s59.73-30.47 89.62-60.93l298.66-304.63h-.47a281.91 281.91 0 0 0 90.06-207.39C957.24 126.91 834.34 1.55 681.21 0z" />
          </svg>
        );
      case 'more':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 955.73 955.73"
          >
            <title>more</title>
            <path d="M477.87 65.16c227.93 0 412.7 184.78 412.7 412.71s-184.77 412.7-412.7 412.7S65.16 705.8 65.16 477.87C65.42 250 250 65.42 477.87 65.16m0-65.16C214 0 0 214 0 477.87s214 477.86 477.87 477.86 477.86-213.94 477.86-477.86S741.79 0 477.87 0zm-141.2 477.87a54.31 54.31 0 1 1-54.3-54.31 54.3 54.3 0 0 1 54.3 54.31zm195.5 0a54.31 54.31 0 1 1-54.3-54.31 54.3 54.3 0 0 1 54.3 54.31zm195.5 0a54.31 54.31 0 1 1-54.3-54.31 54.3 54.3 0 0 1 54.28 54.31z" />
          </svg>
        );
      case 'play':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 1024 1024"
          >
            <defs>
              <linearGradient
                id="a"
                x1="829.02"
                y1="194.98"
                x2="195.54"
                y2="828.46"
                gradientUnits="userSpaceOnUse"
              >
                <stop offset="0" stopColor="#70befe" />
                <stop offset="1" stopColor="#1596ff" />
              </linearGradient>
            </defs>
            <title>play</title>
            <circle cx="512" cy="512" r="512" fill="url(#a)" />
            <path
              d="M367.23,800.1a35.31,35.31,0,0,1-35.31-35.31V259.21a35.31,35.31,0,0,1,55.33-29.09l367.23,252.8a35.31,35.31,0,0,1,0,58.17L508.9,708.39a35.31,35.31,0,0,1-40-58.17L672.18,512,402.54,326.39v438.4A35.31,35.31,0,0,1,367.23,800.1Z"
              fill="#fff"
            />
          </svg>
        );
      case 'setting':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 955.89 989.87"
          >
            <title>setting</title>
            <path d="M478 725.13c-127.13.37-230.49-102.4-230.86-229.53s102.4-230.49 229.53-230.86 230.49 102.4 230.86 229.53v.66C707.52 621.82 604.84 724.8 478 725.13zm0-391.34a161.15 161.15 0 1 0 160.68 161.6v-.46A161.09 161.09 0 0 0 478 333.79zm91.82 656.08H386.13a34.45 34.45 0 0 1-34.25-31.1l-12.26-122.88a363.21 363.21 0 0 1-86.87-50.4l-112.31 50.84a34.37 34.37 0 0 1-44-14.21L4.64 662.63a34.56 34.56 0 0 1 9.71-45.29l99.81-72a368.58 368.58 0 0 1 0-100.95l-99.83-71.88a34.58 34.58 0 0 1-9.71-45.29l91.82-159.49a34.32 34.32 0 0 1 44-14.13l112.33 50.84A362.59 362.59 0 0 1 339.62 154l12.26-122.85A34.45 34.45 0 0 1 386.13 0h183.64A34.46 34.46 0 0 1 604 31.1L616.27 154a362.66 362.66 0 0 1 86.86 50.41l112.35-50.81a34.34 34.34 0 0 1 44 14.22l91.8 159.48a34.6 34.6 0 0 1-9.71 45.3l-99.81 71.94a367.87 367.87 0 0 1 0 101l99.81 72a34.6 34.6 0 0 1 9.71 45.3l-91.82 159.4a34.41 34.41 0 0 1-44 14.21l-112.3-50.84a363.54 363.54 0 0 1-87 50.32l-12.22 122.88a34.47 34.47 0 0 1-34.17 31.06zm-152.53-69.06h121.33l11.27-113.16a34.48 34.48 0 0 1 23.27-29.29 296.15 296.15 0 0 0 101.77-59.07 34.28 34.28 0 0 1 37-5.58l103.51 46.85 60.66-105.35-91.91-66.27a34.59 34.59 0 0 1-13.65-34.82 300.75 300.75 0 0 0 0-118.36 34.56 34.56 0 0 1 13.6-34.76l91.91-66.27-60.64-105.41-103.51 46.84a34.32 34.32 0 0 1-36.9-5.57 296.36 296.36 0 0 0-101.79-59.08 34.52 34.52 0 0 1-23.28-29.29L538.64 69H417.29L406 182.22a34.47 34.47 0 0 1-23.27 29.29A295.9 295.9 0 0 0 281 270.59a34.44 34.44 0 0 1-37 5.57l-103.49-46.84-60.67 105.36 91.9 66.32a34.54 34.54 0 0 1 13.65 34.81 300.75 300.75 0 0 0 0 118.36 34.57 34.57 0 0 1-13.65 34.82l-91.92 66.22 60.67 105.35L244 713.71a34.35 34.35 0 0 1 37 5.58 296.24 296.24 0 0 0 101.77 59.07A34.44 34.44 0 0 1 406 807.65z" />
          </svg>
        );
      case 'share':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 953.01 955.99"
          >
            <title>share</title>
            <path d="M475.15 956C211.16 954.41-1.57 739.13 0 475.14 1.57 213.38 213.39 1.56 475.15 0a32.75 32.75 0 0 1 0 65.48c-227.83.11-412.44 184.88-412.33 412.71s184.88 412.44 412.7 412.33S887.85 705.76 887.85 478a32.58 32.58 0 0 1 65.15 0c-.25 263.83-214 477.66-477.85 478zM909.6 0H648.92a43.66 43.66 0 1 0 0 87.31H804.7l-360.27 362a43.79 43.79 0 0 0 0 61.73 43.26 43.26 0 0 0 61.18.25l.26-.25L866.13 149v156.63a43.44 43.44 0 1 0 86.88 0V0z" />
          </svg>
        );
      case 'wechat':
        return (
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 1024 829.43"
          >
            <title>wechat</title>
            <path
              d="M552.38,46.9C495.44,17.13,428.54,0,358.16,0,253.27,0,158.49,38.09,92.81,99.44c-69.24,64.68-106.48,160-88.18,254.3C19.46,430.2,69,494.54,143.3,546.43L107.48,654.19l125.21-62.8c15.42,3.06,30.67,6.09,45.87,8.76,37.26,6.53,74.31,10.85,113,7.81-33.12-113.33,11.25-217.86,91.18-284.4,63.49-52.86,149.42-81.74,236.78-72C701,164.9,637.91,91.63,552.38,46.9ZM283.77,214.09a41.63,41.63,0,0,1-9.57,15.41c-8.27,8.3-19.43,12.15-31,12.45-15.17.39-31-5.35-41.67-15.16a41.41,41.41,0,0,1-10.25-14.41,39.74,39.74,0,0,1,10.24-45.15c10.68-9.74,26.51-15.45,41.69-15.06,11.54.31,22.7,4.13,31,12.38C286.59,176.89,289.74,197.48,283.77,214.09Zm250,2A41.11,41.11,0,0,1,525,229.49c-8.91,8.92-21.16,12.71-33.6,12.47-14.34-.27-28.94-5.87-39-15.11a41.39,41.39,0,0,1-9.42-12.6,39.82,39.82,0,0,1,9.35-47c10.05-9.21,24.68-14.79,39.05-15.07,12.47-.24,24.74,3.53,33.64,12.4C537.89,177.39,540.78,199.16,533.8,216.08Z"
              fill="#69cf3e"
            />
            <path
              d="M1024,533.67c0-41.46-12-80.7-33-115.54A270.78,270.78,0,0,0,943.56,360c-66.65-62.16-159.39-91.76-249.73-85.39-79.45,5.6-149.51,36.75-199.51,83.62a266.53,266.53,0,0,0-37.47,43.45c-26.58,38.71-41.74,83.84-41.74,131.95,0,73,34.76,139,91.36,186.25,48,40.1,111.81,66.66,183.43,72.48q14.72,1.2,29.86,1.21c35.67,0,71.64-9,107.47-18l98.24,53.8Q912,784.69,898.54,739.92C970.43,686,1024,614.45,1024,533.67Zm-354.61-70a38.06,38.06,0,0,1-10.67,16.41,52.27,52.27,0,0,1-32.07,13.54c-12.48.74-25-3.16-34.4-12.49a41.73,41.73,0,0,1-10.59-17.21c-4.09-13.29-.52-27.82,10.64-39,9.37-9.37,21.92-13.28,34.38-12.53a52.22,52.22,0,0,1,32,13.62C669.94,436.41,673.51,450.78,669.39,463.68ZM866,465.24a38.55,38.55,0,0,1-10.17,14.87,52.52,52.52,0,0,1-34.2,13.72c-11.75.23-23.4-3.72-32.21-12.56a42.19,42.19,0,0,1-10.06-15.63c-4.91-13.8-1.52-29.15,10.1-40.82a43.6,43.6,0,0,1,32.15-12.59A52.47,52.47,0,0,1,855.73,426C867.5,436.79,870.94,451.92,866,465.24Z"
              fill="#69cf3e"
            />
          </svg>
        );
      default:
        return null;
    }
  }
}
