import List from './List';
import ListRow from './List-Row';
import ListDesc from './List-Desc';
import ListInput from './List-Input';
import ListRadio from './List-Radio';
// import ListSwitch from './List-Switch';
import ListSelect from './List-Select';
import ListDatetime from './List-Datetime';
import ListCheckbox from './List-Checkbox';
import ListDashboard from './List-Dashboard';
import ListCardSelect from './List-CardSelect';
import ListVerifymobile from './List-Verifymobile';
List.Row = ListRow;
List.Desc = ListDesc;
List.Input = ListInput;
List.Radio = ListRadio;
// List.Switch = ListSwitch;
List.Select = ListSelect;
List.Datetime = ListDatetime;
List.Checkbox = ListCheckbox;
List.Dashboard = ListDashboard;
List.CardSelect = ListCardSelect;
List.Verifymobile = ListVerifymobile;
export default List;
